import os
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    """
    Standardized configuration loader.
    """
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")
    
    # LLM Providers
    OPENAI_API_KEY: str = ""
    ANTHROPIC_API_KEY: str = ""
    
    # Model Selection (Cost Arbitrage)
    MODEL_FAST: str = "gpt-4o-mini" # For simple tasks
    MODEL_SMART: str = "gpt-4o"      # For complex reasoning
    
    # Project Info
    PROJECT_NAME: str = "Lianhun-Agent"
    VERSION: str = "0.1.0"
    
    # Compliance
    WATERMARK_TEXT: str = "AI-Generated by Lianhun Protocol"

settings = Settings()
